config/routes.rb
AwesomeAnswers::Application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  resources :questions do
    resources :answers
    resources :likes, only: :create do
      delete :destroy, on: :collection
    end
  end

  resources :answers, only: [] do
    resources :likes, only: :create do
      delete :destroy, on: :collection
    end
  end

  resources :discussions do
    post :flag, on: :member
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions
    end
  end

  resources :tips, only: [:new, :create]
  
  root "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :answers, dependent: :destroy

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  has_many :likes, as: :likable
  has_many :likers, through: :likes, source: :user

  validates_presence_of :title, message: "must have something"
  validates_presence_of :body
  validates_numericality_of :like_counter, allow_nil: true
  validates :title, presence: true, uniqueness: true, length: {minimum: 10}

  scope :ten,     -> { limit(10) }
  scope :recent,  -> { where(["updated_at > ?", Time.now - 10.day]) }
  scope :all_but, lambda {|ids| where(["id NOT IN (?)", ids])}

  before_save :capitalize_title, on: :create
  before_save :print1
  after_save :print2

  default_scope { order("updated_at DESC") }


  # def to_param
  #   "#{id} #{title}".parameterize
  # end

  def self.long_titled
    Question.all.select {|q| q.title.length > 30 }
  end

  def self.generate_random_questions(number_of_questions = 100)
    number_of_questions.times do
      random_title = (0...rand(60)).map { ('a'..'z').to_a[rand(26)] }.join
      Question.create(title: random_title, body: "asdfasdfasdf")
    end
  end

  def liked_by? user
    likers.include? user
  end

  def like_by user
    likers << user
    self.like_counter += 1
    save
  end

  def unlike_by user
    likers.delete user
    self.like_counter -= 1
    save
  end

  private

  def capitalize_title
    self.title.capitalize!
  end

  def print1
    Rails.logger.info "Before Save"
  end

  def print2
    Rails.logger.info "After Save"
  end

end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController

  before_filter :restrict_access

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  private

  def restrict_access
    # @api_key ||= ApiKey.find_by_access_token(params[:access_token])
    # head :unauthorized unless @api_key.present?
    authenticate_or_request_with_http_token do |token, options|
      @api_key ||= ApiKey.find_by_access_token(token)
      @api_key.present?
    end
  end

  def api_user
    @api_user ||= @api_key.user
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:edit, :update]

  def index
    @questions = Question.page(params[:page]).per_page(4)
    respond_to do |format|
      format.html { render }
      format.json { render json: @questions.all }
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new question_params
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def show
    @question = Question.friendly.find(params[:id])
    @answer   = Answer.new
  end

  def edit
    
  end

  def update
    if @question.update_attributes question_params
      redirect_to @question, notice: "Question updated successfully."
    else
      render :edit
    end
  end

  private

  def question_params
    params.require(:question).permit([:title, :body, {category_ids: []}])
  end

  def set_question
    @question = current_user.questions.friendly.find(params[:id])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>

  <% if @question.errors.any? %>
    <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>

  <% end %>

  <div class="form-group">
    <%= f.label :title,  "My Title" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>

  <ul>
    <%= hidden_field_tag "question[category_ids][]", nil %>
    <% Category.all.each do |category| %>
      <li>
        <%= check_box_tag "question[category_ids][]", category.id,  @question.categories.include?(category), id: dom_id(category) %>
        <%= label_tag dom_id(category), category.name %>
      </li>
    <% end %>
  </ul>

  <br>
  <%= f.submit "Save", class: "btn btn-primary" %>

<% end %>

app/views/questions/edit.html.erb
<h1> Edit Question</h1>

<%= render "form" %>

app/views/questions/index.html.haml
%h1= t("welcome")

= link_to "<i class='glyphicon glyphicon-plus'></i> New Question".html_safe, new_question_path, class: "btn btn-primary"

- @questions.each do |question|
  %p= link_to question.title, question
  %p= special_truncate(question.body).html_safe
  %p Created On: #{formatted_date question.created_at}
  %hr

= will_paginate @questions, previous_label: "<", next_label: ">", renderer: BootstrapPagination::Rails

app/views/questions/new.html.erb
<h1> Create New Question</h1>

<%= render "form" %>

app/views/questions/show.html.haml
= cache @question, expires_in: 5.minutes do
  %h1
    = I18n.t("question.heading")
    \:
    = @question.title
  %p= @question.body
  %p
    Likes: #{@question.like_counter}
  %p 
    Answers: 
    %span#answer-count
  

%p
  Created by: #{capitalize_name @question.user.name_display}
  - if @question.liked_by? current_user
    = link_to "Un-Like", question_likes_path(@question) , method: :delete, class: "btn btn-danger"
  - else
    = link_to "Like", question_likes_path(@question), method: :post, class: "btn btn-primary"
%hr

.modal.fade.in#edit-question{tabindex: "-1", role: "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
        %h4#myModalLabel.modal-title Modal title
      .modal-body
        \...
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
        %button.btn.btn-primary{type: "button"} Save changes


- if can? :manage, @question
  = link_to "Edit", edit_question_path(@question), class: "btn btn-info", remote: true, "data-toggle" => "modal", "data-target" =>"#edit-question"

  = link_to "Delete", @question, class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"}
- if @answer.errors.any?
  %ul
    - @answer.errors.each do |msg|
      %li= msg.inspect
.centered-image
  = image_tag "imgres.jpg"

= render "/answers/form", question: @question, answer: @answer

%br
%h2 Answers
#answers
  - @question.answers.each do |answer|
    = render "/answers/answer", answer: answer
= link_to t("question.all_questions"), questions_path