config/routes.rb
AwesomeAnswers::Application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  resources :questions do
    resources :answers
    resources :likes, only: :create do
      delete :destroy, on: :collection
    end
  end

  resources :answers, only: [] do
    resources :likes, only: :create do
      delete :destroy, on: :collection
    end
  end

  resources :discussions do
    post :flag, on: :member
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions
    end
  end

  resources :tips, only: [:new, :create]
  
  root "questions#index"

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :authenticate_user!

  def new
  end


  def create
    charge = Stripe::Charge.create( amount: params[:amount].to_i * 100,
                                   currency: "cad",
                                   card: params[:stripe_card_token],
                                   description: "Tip from #{current_user.email}")
    if charge["paid"]
      redirect_to root_path, notice: "Thank you for tipping us, you're awesome!"
    else
      flash.now[:notice] = "Sorry we couldn't charge your card"
      render :new
    end
  end

end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/new.html.haml
#stripe-error.alert-danger

.form-group
  = label_tag "card_number"
  = text_field_tag "card_number", '' , class: "form-control"
%br
.form-group
  = label_tag "card_month", "Expiry"
  .row
    .col-sm-6= select_month nil, {add_month_numbers: true}, {id: "card_month", class: "form-control"}
    .col-sm-6= select_year nil, {start_year: Date.today.year, end_year: Date.today.year + 10}, {id: "card_year", class: "form-control"}
%br
.form-group
  = label_tag "card_cvc"
  = text_field_tag "card_cvc", nil, class: "form-control"
%br

= form_tag tips_path, id: "new_tip" do
  = hidden_field_tag "stripe_card_token"
  = label_tag "amount"
  = select_tag "amount", options_for_select([5, 10, 15, 20, 25,30]), class: "form-control"
  %br
  = submit_tag "Submit", class: "btn btn-primary"