config/routes.rb
AwesomeAnswers::Application.routes.draw do
  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}

  resources :questions do
    resources :answers
    resources :likes, only: :create do
      delete :destroy, on: :collection
    end
  end

  resources :answers, only: [] do
    resources :likes, only: :create do
      delete :destroy, on: :collection
    end
  end

  resources :discussions do
    post :flag, on: :member
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :questions
    end
  end

  resources :tips, only: [:new, :create]
  
  root "questions#index"

end

app/views/layouts/_head.html.erb
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<%= javascript_include_tag "https://js.stripe.com/v1/"  %>
<%= tag :meta, name: "stripe-key", content: ENV['STRIPE_PUBLISHABLE_KEY'] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers | <%= yield(:salman) %></title>
  <%= render "/layouts/head" %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <ul class="nav navbar-nav  navbar-left">
    <li><%= link_to "Home", root_path %></li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
    <li class="pull-right">
      <div>
        <% if user_signed_in? %>
          Hello <%= link_to current_user.name_display, edit_user_registration_path %>, 
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign Up", new_user_registration_path %>
          |
          <%= link_to "Sign In", new_user_session_path %>
          |
          <%= link_to "Sign In With Google", user_omniauth_authorize_path(:google_oauth2) %>

        <% end %>
        |
        <%= link_to "Tip us!", new_tip_path %>
        |

        <%= link_to_unless_current "English", locale: "en" %>
        <br>
        <%= link_to "Español", locale: "es" %>

      </div>
    </li>
  </ul>
</nav>


  <% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% elsif flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/discussions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= render "/layouts/head" %>
</head>
<body>

  <% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% elsif flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>